# The URL the site will be built for
base_url = "https://www.freedomlayer.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true
# highlight_theme = "base16-ocean-dark"
# highlight_theme = "cheerfully-light"
highlight_theme = "monokai"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
# Put all your custom variables here

site_name = "Freedomlayer"

site_menu = [
    {url = "$BASE_URL", name = "Freedomlayer"},
    {url = "$BASE_URL/research", name = "Research"},
    {url = "$BASE_URL/offst", name = "Offst"},
    {url = "$BASE_URL/about", name = "About"},
]
